.TH CONVERT-DB 8 "Services for IRC Networks" "" \" -*- nroff -*-
.SH NAME
convert-db \- database conversion program for IRC Services
.SH SYNOPSIS
.B convert-db
[
.I options
] 
[+
.I program-name
] 
.I directory
.SH DESCRIPTION
convert-db is a tool provided with Services for IRC Networks to convert
databases from similar programs to a format which can be read by the
ircservices(8) daemon program.
.PP
There is no manpage documentation; please see the HTML documentation for
details.
