.TH IRCSERVICES 8 "Services for IRC Networks" "" \" -*- nroff -*-
.SH NAME
ircservices \- Services for IRC Networks daemon program
.SH SYNOPSIS
.B ircservices
[
.I options
]
.SH DESCRIPTION
Services for IRC Networks (also known as IRC Services or just Services)
provides nickname and channel registration and many other services for
use on IRC (Internet Relay Chat) networks.
.PP
There is no manpage documentation; please see the HTML documentation for
details.
