.TH IRCSERVICES 8 "Services for IRC Networks" "" \" -*- nroff -*-
.SH NAME
ircservices \- Services for IRC Networks daemon program
.SH SYNOPSIS
.B ircservices-chk
[
.I options
]
.SH DESCRIPTION
\fBircservices-chk\fR checks whether Services for IRC Networks
(\fBircservices\fR) is running, and restarts it with the supplied options
if not.
.PP
Please see the HTML documentation (section 2-5 in particular) for details.
