# Makefile for StatServ modules.
#
# IRC Services is copyright (c) 1996-2009 Andrew Church.
#     E-mail: <achurch@achurch.org>
# Parts written by Andrew Kempe and others.
# This program is free but copyrighted software; see the file GPL.txt for
# details.

###########################################################################

include ../../Makefile.inc

MODULES = main.so

INCLUDES = statserv.h $(TOPDIR)/commands.h $(TOPDIR)/databases.h \
	$(TOPDIR)/language.h $(TOPDIR)/modules/operserv/operserv.h

include ../Makerules

###########################################################################
